### ISSUE TITLE
Todo before new release

### ISSUE THREAD

**Issue by wiiznokes** [wiiznokes/fan-control#119]
- [x] clean graph code
- [x] remove or upgrade time to update
- [ ] pass compilation on windows
- [ ] dialog to save on exit
- [ ] dialog explanation on Flatpak
- [ ] closing the main window should exit the graph one
- [ ] use yy:mm format for version https://github.com/wiiznokes/fan-control/issues/124
